### ISSUE TITLE
Version of Python?

### ISSUE THREAD

**Issue by stancel** [glasserc/rst2wp#15]
I ran into some issues trying to install and run this program (using Python 3.7.3). Made some adjustments but ran into a few more. I use Pyenv and it is very easy to just run a specific version of Python for each application. I think doing that will be easier at this point than continually updating the code. Would you mind letting me know what version of Python that should work out of the box for this application? Thanks in advance for your time and help.

**Comment by glasserc** [comment]
Hi! Thanks for your interest!

To be honest, I don't know off the top of my head what specific version it will require. It was certainly written in a time of Python 2 and I haven't kept up to date with version upgrades. (But, patches welcome!) I haven't run it on any of the laptops I'm currently operating on so I can't just check there. I imagine 2.7 would work but I can't promise anything.

I'd be remiss if I didn't say that if you are starting a new blog from scratch these days, I would probably not recommend `rst2wp` -- I wouldn't even recommend it for myself except that I already have two blogs running Wordpress that I update in this manner (but not frequently...). These days I would probably suggest a static site builder. I've heard good things about [Pelican](https://blog.getpelican.com/).

Sorry I can't help more! I'll try to make some time in the near future to update this project and I'll post to this bug if I do.

**Comment by stancel** [comment]
Thanks so much @glasserc! Appreciate the response. I'll give Pelican a look as well as trying Python 2.7 with this project. If I do update the project to use Python 3.x, I will submit a pull request. Thanks for your quick response and guidance!

**Comment by glasserc** [comment]
I took a little while tonight to try to do the port myself. You can see the results in #16. Feel free to try that out if you like!

**Comment by glasserc** [comment]
I decided to merge my Python 3 PR so I'm closing this now.
